name: CI

on:
  push:
    branches:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#excluding-paths
    - '*'
    - '!**gpu'

jobs:
  test:
    # https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments
    runs-on: ubuntu-18.04

    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables
    env:
      PYTHONWARNINGS: 'ignore'

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Resolve Dependencies
      - run: |
      pip install -U pytest
      pip install -f https://download.pytorch.org/whl/torch_stable.html torch==1.6.0+cpu
      pip install -r requirements.txt
    
    - name: Set up Quiver & Run Test
      - run: |
      pip install --no-index .
      pytest tests/python/cpu
